/**
 * Downloads the four Met Open Access photographs, grades them to match the
 * card system, writes them into assets/artwork/ and regenerates
 * src/share/artworkAssets.ts.
 *
 *   npm install --save-dev sharp
 *   npx tsx tools/fetch-artwork.ts
 *
 * Nothing here is committed: the images are fetched, not vendored, and every
 * source is verified against the Met's collection API before it is written to
 * disk, so a work that ever stops being open access fails the run loudly
 * instead of silently shipping.
 *
 * Grading matters more than it sounds. Four museum photographs shot under four
 * different lighting setups on four different grounds look like four
 * screenshots, not one product. Pulling most of the colour out, matching the
 * black point and cropping to a consistent aspect is what turns them into a
 * set.
 */
import fs from 'node:fs';
import path from 'node:path';
import { ARTWORK_LIST, Artwork } from '../src/share/artwork';
import { CARD_PIXELS, grade } from './artworkGrade';

const OUT_DIR = path.resolve(process.cwd(), 'assets/artwork');
const GENERATED = path.resolve(process.cwd(), 'src/share/artworkAssets.ts');
const API = 'https://collectionapi.metmuseum.org/public/collection/v1/objects';

/**
 * Re-checks the licence at fetch time rather than trusting the constant in the
 * registry. The Met can and does revise provenance.
 */
async function verifyPublicDomain(art: Artwork): Promise<string> {
  const res = await fetch(`${API}/${art.objectId}`);
  if (!res.ok) throw new Error(`Met API ${res.status} for object ${art.objectId}`);
  const data = (await res.json()) as {
    isPublicDomain: boolean;
    title: string;
    primaryImageSmall: string;
    primaryImage: string;
  };

  if (!data.isPublicDomain) {
    throw new Error(
      `Object ${art.objectId} ("${data.title}") is no longer flagged public domain — ` +
        `do not ship this image.`
    );
  }
  const url = data.primaryImageSmall || data.primaryImage;
  if (!url) throw new Error(`Object ${art.objectId} has no image URL`);
  if (url !== art.imageUrl) {
    console.log(`  note: the Met's image URL moved, using theirs\n        ${url}`);
  }
  return url;
}

async function download(url: string): Promise<Buffer> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} fetching ${url}`);
  return Buffer.from(await res.arrayBuffer());
}


async function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const written: { id: string; file: string; bytes: number }[] = [];

  for (const art of ARTWORK_LIST) {
    console.log(`\n${art.shortName} — Met object ${art.objectId}`);
    const url = await verifyPublicDomain(art);
    console.log('  licence: public domain (CC0) confirmed');

    const raw = await download(url);
    console.log(`  downloaded ${(raw.length / 1024).toFixed(0)} KB`);

    const out = await grade(raw, art);
    const file = path.join(OUT_DIR, `${art.id}.jpg`);
    fs.writeFileSync(file, out);
    console.log(`  wrote ${path.relative(process.cwd(), file)} (${(out.length / 1024).toFixed(0)} KB)`);

    written.push({ id: art.id, file: `${art.id}.jpg`, bytes: out.length });
  }

  const body = `import type { ImageSourcePropType } from 'react-native';

/**
 * GENERATED by tools/fetch-artwork.ts — do not edit by hand.
 *
 * Photographs from the Metropolitan Museum of Art's Open Access collection,
 * each verified as public domain (CC0) at fetch time. Provenance and credits
 * live in src/share/artwork.ts.
 */
export const ARTWORK_IMAGES: Record<string, ImageSourcePropType> = {
${written.map((w) => `  ${w.id}: require('../../assets/artwork/${w.file}'),`).join('\n')}
};

export const ARTWORK_FETCHED_AT: string | null = '${new Date().toISOString()}';
`;

  fs.writeFileSync(GENERATED, body);
  console.log(`\nRegenerated ${path.relative(process.cwd(), GENERATED)}`);

  const total = written.reduce((n, w) => n + w.bytes, 0);
  console.log(`${written.length} images, ${(total / 1024 / 1024).toFixed(2)} MB total\n`);
}

main().catch((err) => {
  console.error(`\n${err.message}\n`);
  process.exit(1);
});
